language: node_js

node_js: node

cache:
  directories:
    - node_modules

script:
  - yarn test
  - bash <(curl -s https://codecov.io/bash)
  - yarn build
  - yarn bundlesize --enable-github-checks

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        script: yarn semantic-release
