language: node_js

node_js: node

cache:
  directories:
    - node_modules

script:
  - yarn test
  - bash <(curl -s https://codecov.io/bash)
  - yarn bundlesize

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
